COMPILER = g++
 user:user.cpp
	g++ user.cpp -o user `pkg-config --cflags opencv` `pkg-config --libs opencv` '--std=c++11'
 target:target.cpp
	g++ target.cpp -o target `pkg-config --cflags opencv` `pkg-config --libs opencv` '--std=c++11'

